version: "3"
networks:
  restaurant-network:
    driver: bridge

services:
  backend:
    container_name: webserver
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    restart: on-failure
    networks:
      - restaurant-network

  frontend:
    container_name: website
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    environment:
      - HUB_HOST=webserver
      - HUB_PORT=8888
      - VUE_APP_ROOT_API=http://localhost:8888/api/v1
    ports:
      - "7778:80"
    restart: on-failure
    networks:
      - restaurant-network
    depends_on:
      - backend
