version: "3"
services:
  restaurant_backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"

  restaurant_frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "7777:8080"
    depends_on:
      - restaurant_backend
