version: "3"
networks:
  restaurant-network:
    driver: bridge

services:
  backend:
    container_name: webserver
    build:
      context: ../../backend
      args:
        NODE_ENV: development
        MYSQL_HOST: mysql.host
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: restaurant
        MYSQL_PORT: 3306
        BACKEND_PORT: 8888
    ports:
      - "8888:8888"
    restart: on-failure
    networks:
      - restaurant-network

  frontend:
    container_name: website
    build:
      context: ../../frontend
      args:
        VUE_APP_ROOT_API: http://localhost:8888/api/v1
        VUE_APP_ALLOWED_HOST: .sctp-sandbox.com
    environment:
      - HUB_HOST=webserver
      - HUB_PORT=8888
      - VUE_APP_ROOT_API=http://localhost:8888/api/v1
    ports:
      - "7778:80"
    restart: on-failure
    networks:
      - restaurant-network
    depends_on:
      - backend
