apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-restaurant
  namespace: restaurant
spec: 
  ingressClassName: nginx
  rules:
  - host: "ce5-group2-food.sctp-sandbox.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 7778
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: backend-service
              port:
                number: 7777
