name: Build and push Frontend/Backend image to ECR
run-name: ${{ github.actor }} is running ECR build-and-push on GitHub Actions 🚀
on:
  pull_request:
  workflow_dispatch:
      inputs:
        branch:
          description: 'The branch to build'
          required: true
        environment:
          description: 'The environment to deploy to'
          required: false
  push:
    branches:
      - feature/ci-build-docker-image-ecr

env:
  ECR_ENDPOINT: public.ecr.aws/u2q1a2y8
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: Get changed files with predefined action
        id: changed-files
        uses: tj-actions/changed-files@v37
  
      - name: List all changed files
        run: |
          echo '# FILES with tj-actions/changed-files' >> "${GITHUB_STEP_SUMMARY}"
          echo '' >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

          files_list=${{ steps.changed-files.outputs.all_changed_files }}
          for file in ${files_list}; do
            echo "$file was changed" >> "${GITHUB_STEP_SUMMARY}"
          done

          echo '```' >> "${GITHUB_STEP_SUMMARY}"

          # save files into variable
          printf 'THE_FILES=%s\n' "${files_list}" >> "${GITHUB_ENV}"
           
      - name: Get docker image names
        shell: python
        env:
          PROJECT_IMAGE_MAP: '{"backend": ${{ vars.BACKEND_IMAGE_NAME }}, "frontend": ${{ vars.FRONTEND_IMAGE_NAME }}}'
        run: |
          from os import environ
          import json
          
          # split files string into list. Divide by spaces
          files = environ.get("THE_FILES").split(' ')
          print(files)
          proj_image_map = json.loads(environ.get("PROJECT_IMAGE_MAP"))

          images = []

          # check if backend, frontend, etc is a part of changed file path
          for file in files:
            for k, v in proj_image_map.items():
              if k in file:
                if v not in images:
                  images.append(v)

          # save retreived images as json array
          with open(environ.get("GITHUB_ENV"), 'a') as f:
            f.write('IMAGES_TO_BUILD=' + json.dumps(images) + '\n')

      - name: Set image names as output for matrix
        id: set_images
        run: |
          echo "IMAGES_TO_BUILD=${IMAGES_TO_BUILD}" >> $GITHUB_OUTPUT

  print_image_names_with_matrix:
    name: "Build image: ${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson( needs.get_manually.outputs.IMAGES_TO_BUILD ) }} 
    steps:
      - name: Print image name from matrix
        run: |
          echo "${{ matrix.image }}"



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to AWS ECR
        id: login-ecr
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_ENDPOINT }}
        
      - name: Build and push Docker image for backend
        working-directory: ./backend
        if: env.FOLDER_CHANGED == 'backend'
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ vars.BACKEND_IMAGE_NAME }} .
          docker push ${{ env.ECR_ENDPOINT }}/${{ vars.BACKEND_IMAGE_NAME }}:$IMAGE_TAG

      - name: Build and push Docker image for frontend
        working-directory: ./frontend
        if: env.FOLDER_CHANGED == 'frontend'
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ vars.FRONTEND_IMAGE_NAME }} .
          docker push ${{ env.ECR_ENDPOINT }}/${{ vars.FRONTEND_IMAGE_NAME }}:$IMAGE_TAG
      
      
      
      
      
      

#
#      - name: Frontend docker build and tag
#        run: |
#          docker build -t ${{ vars.FRONTEND_IMAGE_NAME }} .
#          docker tag ${{ vars.IMAGE_NAME }}:latest ${{ env.ECR_ENDPOINT }}/${{ vars.FRONTEND_IMAGE_NAME }}:latest
#      - name: Run frontend image scan
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: '${{ vars.FRONTEND_IMAGE_NAME }}:latest'
#          format: 'table'
#          # exit-code: '1'
#          ignore-unfixed: true
#          vuln-type: 'os,library'
#          severity: 'MEDIUM,HIGH,CRITICAL'
#          output: 'frontend-docker-image-scan.json'
#      - name: Upload Docker Trivy Report
#        uses: actions/upload-artifact@v4.3.0
#        with:
#          name: docker-image-scan
#          path: docker-image-scan.json
#      - name: Docker publish to ECR
#        run: docker push ${{ env.ECR_ENDPOINT }}/${{ vars.FRONTEND_IMAGE_NAME }}:latest
