name: Code Vulnerability Scan
run-name: ${{ github.actor }} is running Code Scanning on GitHub Actions 🚀
on: [push]
jobs:
  frontend-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

  code-ql-scanning:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"


  frontend-code-vulnerability-scanning:
    runs-on: ubuntu-latest
    needs: [frontend-install-dependencies, code-ql-scanning]
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd frontend
          snyk test --severity-threshold=critical
          snyk test --severity-threshold=critical --json > frontend-snyk-results.json

      - name: Upload Snyk Scan Results
        uses: actions/upload-artifact@v4.3.0
        with:
          name: snyk-scan-results
          path: frontend-snyk-results.json

  backend-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install
  
  backend-code-vulnerability-scanning:
    runs-on: ubuntu-latest
    needs: [backend-install-dependencies, code-ql-scanning]
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd frontend
          snyk test --severity-threshold=critical
          snyk test --severity-threshold=critical --json > backend0snyk-results.json

      - name: Upload Snyk Scan Results
        uses: actions/upload-artifact@v4.3.0
        with:
          name: snyk-scan-results
          path: backend-snyk-results.json

  iac-vulnerability-scanning:
    runs-on: ubuntu-latest
    needs: [frontend-install-dependencies, code-ql-scanning]
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Code Scan And Check Snyk Scan Results
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk iac test --severity-threshold=critical
          snyk iac test --severity-threshold=critical --json > snyk_iac_report.json
      - name: Upload Snyk IaC Report
        uses: actions/upload-artifact@v4.3.0
        with:
          name: snyk-iac-report
          path: snyk_iac_report.json

  build_summary:
    needs: [frontend-code-vulnerability-scanning, iac-vulnerability-scanning]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          FRONTEND_CODE_SCAN_STATUS=${{ needs.frontend-code-vulnerability-scanning.outputs.status }}
          IAC_SCAN_STATUS=${{ needs.iac-vulnerability-scanning.outputs.status }}

          echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name                 | Status                     |" >> $GITHUB_STEP_SUMMARY
          echo "|--------------------------|----------------------------|" >> $GITHUB_STEP_SUMMARY
          echo "| frontend-code-scan       | $FRONTEND_CODE_SCAN_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| backend-code-scan        | $BACKEND_CODE_SCAN_STATUS  |" >> $GITHUB_STEP_SUMMARY
          echo "| iac-scan                 | $IAC_SCAN_STATUS           |" >> $GITHUB_STEP_SUMMARY
